### ISSUE TITLE
Decided on how we want to implement purchases

### ISSUE THREAD

**Issue by kyhorne** [kyhorne/booksrus#9]
Should all books of the same type have the same price? Should the user decide the price of the book? This will affect our database schema.

**Comment by devonverge** [comment]
The person(owner) uploading should be the one setting the price for the user to buy I feel.

**Comment by kyhorne** [comment]
I agree. We can discuss more in the lab tomorrow. I made an ER diagram that we can use for our database schema. It is simple; however, we can add more complexity at a later date (i.e. purchase price, purchase time).

<img width="865" alt="Screen Shot 2020-03-03 at 4 41 01 PM" src="https://user-images.githubusercontent.com/47677604/75822515-16e34400-5d6e-11ea-9a08-30173886ff64.png">

**Comment by kyhorne** [comment]
I am not that confident with databases so if you have a better solution we can go with that.

**Comment by tanishagarg2** [comment]
Quick question, what if two users upload the same book but with different prices, are we going to keep both the books ?

**Comment by kyhorne** [comment]
This would probably be more appropriate.

<img width="883" alt="Screen Shot 2020-03-03 at 5 10 15 PM" src="https://user-images.githubusercontent.com/47677604/75824649-e30a1d80-5d71-11ea-9a5e-5c4c90e86b5d.png">

**Comment by kyhorne** [comment]
A user can upload zero or many products, and a product has one book. Now a new entry in the product table will always be created when a user uploads a book.

**Comment by kyhorne** [comment]
> Quick question, what if two users upload the same book but with different prices, are we going to keep both the books ?

A user can upload zero or many products, and a product has one book. Now a new entry in the product table will always be created when a user uploads a book. The book table will always contain unique books since the ISBN is the primary key.

**Comment by RobynVG** [comment]
So just to catch up here. We're doing like a kijiji type thing where everyone has the same roles? This looks good to me. The only thing I'm trying to wrap my head around is distinguishing user relationships with the objects as sellers or previous buyers. Or maybe instead of maitaining old records we can keep some kind of a log outside of the database?

**Comment by kyhorne** [comment]
I don't think it is necessary to distinguish users as sellers or buyers because they both have the same privileges.

**Comment by devonverge** [comment]
I agree with you Kyle, I think anyone should be able to buy and/or sell books without restriction

**Comment by RobynVG** [comment]
I was thinking more in terms of how we're going to implement recommendations. The schema seems to be for books that are currently posted and are linked to the seller. We'll also need to log all transactions and their buyers.

**Comment by tanishagarg2** [comment]
The Prof. recommended using Jaccard distance for book recommendations so we will have research on how we can implement it in our system

**Comment by RobynVG** [comment]
Yeah I looked into recommendations and have a few comments for that but I do think how we implement it will affect our schema

**Comment by devonverge** [comment]
> 
> 
> The Prof. recommended using Jaccard distance for book recommendations so we will have research on how we can implement it in our system

Make this an issue

**Comment by RobynVG** [comment]
I was going to bring up my recommendations concern in the lab so I just want to expand and clarify before we move ahead with this.

As mentioned we need to log past purchases. (Although maybe we are from the schema tbh I don't understand it 100%)

The other thing is that Jaccard distance compares 2 sets. An easy approach would be to compare users on the set of books they have purchased. If books are all unique in the system however, we can't do this. I'm not opposed to the idea but just suggest we have a plan on how we will be implementing the recommendations feature before moving ahead with the schema.

**Comment by kyhorne** [comment]
I renamed two tables in the ER diagram. 

<img width="853" alt="Screen Shot 2020-03-06 at 1 34 53 PM" src="https://user-images.githubusercontent.com/47677604/76111949-4765f080-5faf-11ea-84ac-cbdc95724392.png">

So I propose that we have four tables: User, Buyer, Seller, Book. When you register a new account, your information is inserted in the User table with your username being the primary key. A user can post a new advertisement selling a book; in this case, a new entry is added to the Seller table with the user's username and the ISBN of the book they are selling acting as foreign keys. Therefore, if we want to see all the selling prices of a specific book, we can query the Seller table with the ISBN of the book. Likewise, if we want to see all the advertisements of any particular user, we can query the Seller table with the user's username. Moreover, if a user buys a book, a new entry is added to the Buyer table with the user's username and the ISBN of the book they purchased acting as the foreign keys. If we want to see all purchases that any particular user has made, then we can query the Buyer table with the user's username.

For recommendations of a particular user, we can compare the purchases of that user to the purchases of every other user (like you said) by using the Buyer table. The output will be a list of values between zero to one, with one being the user with the most similar purchases. We could then find the difference between the user with the most similar purchases to determine a good recommendation. Also, it is essential to note that an output of one means the sets are the same; we will need to discard these values because they will not aid in providing a good recommendation. Additionally, the Jaccard Index does not work well with a small sample size; therefore, we may not get a good result.

**Comment by RobynVG** [comment]
Okay sounds good I guess I misunderstood the diagram in particular the order/buyer table.

**Comment by RobynVG** [comment]
I created a pr for the corresponding model. The only flexibility was the direction of the relationships for the class diagram. I made everything uni-directional so, for example, Product has a user but a user does not have a list of products

**Comment by kyhorne** [comment]
As per phone call: 
<img width="617" alt="Screen Shot 2020-03-14 at 6 41 13 PM" src="https://user-images.githubusercontent.com/47677604/76691653-69044f00-6623-11ea-9ee0-21c3ed211c1e.png">

**Comment by RobynVG** [comment]
Hey so from working on authentication I have a 2 small suggested changes.
  1 Removing salt from the User Table 
    -> The method I used concatenates the salt with the password. Other methods would require some kind of work around 
  2 Renaming Buyer Table  
    -> I was under the impression that we renamed it temporarily because I had a hard time understanding the schema (I'm not sure the name now really reflects the contents). Although, we can't name it Order because its an sql key word. BookOrder is my suggestion.

These changes are pretty small so I don't think we need to be in a rush to update the er diagram but I figured I should still mention changes I intend to put in the model that would effect the database in case you guys disagree

**Comment by kyhorne** [comment]
> Hey so from working on authentication I have a 2 small suggested changes.
> 1 Removing salt from the User Table
> -> The method I used concatenates the salt with the password. Other methods would require some kind of work around
> 2 Renaming Buyer Table
> -> I was under the impression that we renamed it temporarily because I had a hard time understanding the schema (I'm not sure the name now really reflects the contents). Although, we can't name it Order because its an sql key word. BookOrder is my suggestion.
> 
> These changes are pretty small so I don't think we need to be in a rush to update the er diagram but I figured I should still mention changes I intend to put in the model that would effect the database in case you guys disagree

Sounds good to me! I will update the ER diagram.
